//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practice_gor_k700
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecificationsOfPart
    {
        public int idScpecification { get; set; }
        public int idPart { get; set; }
        public decimal value { get; set; }
    
        public virtual DevicePart DevicePart { get; set; }
        public virtual Specifications Specifications { get; set; }
    }
}
